### ISSUE TITLE
No muestra nuevos colaboradores añadidos

### ISSUE THREAD

**Issue by edugon4** [unicah/portfolioManager#23]
No muestra nuevos colaboradores añadidos en portafolios o documentos, elemento que si funcionaba con anterioridad.
![pantalla](https://user-images.githubusercontent.com/26447655/28552070-756d257c-70a9-11e7-9258-8a344ac046b7.png)

**Comment by obetancourthunicah** [comment]
Corregido, coordinadores vuelvan a rebase su base para propagar
